# Questo è il file di esempio che useremo all' esame e da dare al prof che scricherà
# mettendo le nostre credenziali in modo sicuro
brevo.api.key=INSERISCI_QUI_LA_TUA_CHIAVE_API
brevo.mittente=la_tua_mail@example.com
brevo.destinatario=destinatario@example.com